### ISSUE TITLE
Support multiple Steam libraries

### ISSUE THREAD

**Issue by emar10** [cyberrumor/ammo#26]
At the moment AMMO only looks for supported games in `$HOME/.local/share/Steam/steamapps/common`, meaning games installed in other Steam libraries are not detected.

`libraryfolders.vdf` located in the main `steamapps` directory could be used to locate additional libraries to search.

**Comment by cyberrumor** [comment]
Oh nice, I had no idea Steam did that, though I have noticed that file before. What do you do in steam that manipulates that file? Add a non steam game?

**Comment by emar10** [comment]
The Storage tab in Steam's settings allows adding libraries and moving games between them. On desktop this is mainly useful for storing games on a separate data partition/drive, this is also how SD card support works on the Steam Deck.

As far as getting library locations out of `libraryfolders.vdf`, it uses Valve's own plaintext key/value format, so a quick parser to just grab all configured library paths would do the trick. I'd be happy to contribute if you're open to PRs.

**Comment by cyberrumor** [comment]
I just pushed some contribution guidelines. Feel free to throw down a PR (or just wait a while, I'll get it added eventually if you don't). Thanks either way :)

**Comment by cyberrumor** [comment]
Ty!
