### ISSUE TITLE
can't load any games

### ISSUE THREAD

**Issue by gteachey** [cyberrumor/ammo#43]
What am I doing wrong?

I'm using Python 3.11, it appears the install is successful, I'm using legal copies of Skyrim AE and Fallout 4, yet both return this when I run ammo.

 ```
index | Game
-------|-----
[0]     Skyrim Special Edition (unknown)
[1]     Fallout 4 (unknown)

>_: 1
Traceback (most recent call last):
  File "/home/glteach/.local/bin/ammo", line 7, in <module>
    ui.repl()
  File "/home/glteach/.local/lib/python3.11/site-packages/ammo/ui.py", line 374, in repl
    command.func(*prepared_args)
  File "/home/glteach/.local/lib/python3.11/site-packages/ammo/game_controller.py", line 131, in <lambda>
    setattr(self, str(i), lambda self, i=i: self._manage_game(i))
                                            ^^^^^^^^^^^^^^^^^^^^
  File "/home/glteach/.local/lib/python3.11/site-packages/ammo/game_controller.py", line 163, in _manage_game
    raise TypeError(
TypeError: Expected [<Source.UNKNOWN: 'unknown'>, <Source.STEAM: 'steam'>, <Source.FLATPAK: 'flatpak'>] but got Source.UNKNOWN of type <enum 'Source'>
```

I wanted to try this out for Fallout 4, I have a pretty modded Skyrim but tried reinstalling fresh copies of both when Fallout 4 wouldn't work. I tried reinstalling ammo, rebooting, setting up a conda environment for it to see if I had some global library issue.  I just get the same error no matter what I try so far.

**Comment by cyberrumor** [comment]
This is still a useful report, thank you! I'll take a look at this. Glad you got it figured out :)

**Comment by cyberrumor** [comment]
This should be fixed now. To get this to work correctly, I had to drop flatpak-specific ammo dir support. Now ammo will use ~/.local/share/ammo for all installation instances of Steam.

If you had games installed via Flatpak that were using the default steam library location, pulling this update will require you to either reactivate/reorder your mods and commit, or move `~/.var/app/com.valvesoftware.Steam/.local/share/ammo` to `~/.local/share/ammo`.

If you didn't have games installed via Flatpak using the default steam library location, you shouldn't have to do anything.

Theoretically you can now move your game back to your preferred drive.
