### ISSUE TITLE
Allow user to change dir locations

### ISSUE THREAD

**Issue by duran55** [cyberrumor/ammo#44]
Can you please add a conf file where below paths can be set by the user:

to change mod downloads path from ~/Downloads to something else.
to change ammo_conf_dir and ammo_mods_dir paths.

**Comment by cyberrumor** [comment]
Yeah, I can do that. I'll probably make these arguments, then you can add those arguments to an alias if you need them to persist.

**Comment by cyberrumor** [comment]
Let me know if this suits your needs: https://github.com/cyberrumor/ammo/commit/087b45c201bb96d9c2b85fa35b5e4cd21c7b1a25

**Comment by duran55** [comment]
Yeah, this seems will do the work. Thank you very much :+1:

**Comment by ethanmoss** [comment]
Hey man, really loving ammo so far.

Would it be possible to document the changes listed in commit 087b45c201bb96d9c2b85fa35b5e4cd21c7b1a25 in the readme/wiki?

I use my ~/Downloads folder for other stuff than mods and it'll be helpful to put them in a specific directory via the changes listed here.
